{% set name = "lhcb-simpletools" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cofitzpa/simpletools/archive/v{{ version }}.tar.gz
  sha256: 946984587505dd3d9147eac4798a7b3ab110a43872bc70ad4c8cd401d8783b90

build:
  number: 23
  skip: true  # [win]
  ignore_run_exports_from:
    # needs CMake metadata to build but doesn't link
    - libboost-devel

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root_base
    - libboost-devel
  run_constrained:

test:
  requires:
    - scikit-hep-testdata
  commands:
    # Some tests are disabled due to https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3533928
    - FN=$(python -m skhep_testdata cms_hep_2012_tutorial/data.root)  # [true]
    - cutapplier "${FN}" events "NJet>2" test_cut.root  # [true]
    - cuttester "${FN}" events "${RECIPE_DIR}/cuts.txt"  # [true]
    - tuplesampler "${FN}" events 0.3 1234 test1.root test2.root  # [true]
    - columnmaker "${FN}" events "Jet_E**2" Jet_E2 test_col.root  # [true]
    - which stacker
    - which stackergen
    - which crop

about:
  home: https://github.com/cofitzpa/simpletools
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Handy command line tools for ntuple manipulation and analysis
  doc_url: https://cds.cern.ch/record/1223091
  dev_url: https://github.com/cofitzpa/simpletools

extra:
  recipe-maintainers:
    - chrisburr
