{% set name = "lhcb-simpletools" %}
{% set version = "3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cofitzpa/simpletools/archive/v{{ version }}.tar.gz
  sha256: 946984587505dd3d9147eac4798a7b3ab110a43872bc70ad4c8cd401d8783b90

build:
  number: 11
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root_base
    - boost-cpp
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - scikit-hep-testdata
  commands:
    - FN=$(python -m skhep_testdata cms_hep_2012_tutorial/data.root)
    - cutapplier "${FN}" events "NJet>2" test_cut.root
    - cuttester "${FN}" events "${RECIPE_DIR}/cuts.txt"
    - tuplesampler "${FN}" events 0.3 1234 test1.root test2.root
    - columnmaker "${FN}" events "Jet_E**2" Jet_E2 test_col.root
    - which stacker
    - which stackergen
    - which crop

about:
  home: https://github.com/cofitzpa/simpletools
  license: GPL-2.0-only
  license_file: LICENSE
  summary: Handy command line tools for ntuple manipulation and analysis
  doc_url: https://cds.cern.ch/record/1223091
  dev_url: https://github.com/cofitzpa/simpletools

extra:
  recipe-maintainers:
    - chrisburr
